### ISSUE TITLE
Flush DB before reassigning

### ISSUE THREAD

**Issue by vitawasalreadytaken** [stlk/dokku-redis-db-id#1]
When an app is deleted, its REDIS_DB is freed up and may be assigned to a new app. The database should be [flushed](http://redis.io/commands/FLUSHDB) before this happens so that apps do not share any state.

How about implementing this as a [post-delete hook](http://progrium.viewdocs.io/dokku/development/pluginhooks)?

**Comment by stlk** [comment]
Great point. We have few ways how we can accomplish it, depending on how important is this issue to you.
1) Request addition of `FLUSHDB` command to ohardy/dokku-redis
2) Do PR to ohardy/dokku-redis
3) Copy connection related code and send command to redis from this plugin

What do you think?

**Comment by vitawasalreadytaken** [comment]
Sending a PR will take like 10 minutes, right? Just add a new command to https://github.com/ohardy/dokku-redis/blob/master/commands
